### ISSUE TITLE
Is there a way to have a placeholder ONLY in the first block? (Please see the image).

### ISSUE THREAD

**Issue by nicokvara** [editor-js/awesome-editorjs#43]
I'd like to avoid this:
![CleanShot 2021-09-14 at 18 10 15@2x](https://user-images.githubusercontent.com/79981174/133273524-37a5ceb9-aa00-49fc-8d4c-e5f4881b5c46.png)

Every time user clicks enter a new block spawns and every new block has a place holder. Would be awesome if place holder followed the cursor like in Notion instead of just appearing inside every block.

**Comment by talyguryn** [comment]
To report and resolve any problems with Editor.js, please open issues in the core repo or the plugin.

https://github.com/codex-team/editor.js

https://github.com/editor-js/paragraph

Thank you.

**Comment by VityaSchel** [comment]
```css
.ce-block:first-child > .ce-block__content > .ce-paragraph::before {
  display: block;
}
.ce-block > .ce-block__content > .ce-paragraph::before {
  display: none;
}
```
When using svelte or css modules:
```css
:global(.ce-block:first-child > .ce-block__content > .ce-paragraph::before) {
  display: block;
}
:global(.ce-block > .ce-block__content > .ce-paragraph::before) {
  display: none;
}
```
